# Generated by Django 2.2.5 on 2019-09-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P1', models.TextField(max_length=300)),
                ('P2', models.TextField(max_length=300)),
                ('P3', models.TextField(max_length=300)),
                ('P4', models.TextField(max_length=300)),
                ('P5', models.TextField(max_length=300)),
                ('P6', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=50)),
                ('img1', models.CharField(max_length=50)),
                ('img2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=250)),
                ('news', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmm', to='News.New')),
            ],
        ),
    ]
