# Generated by Django 2.2.5 on 2019-09-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190927_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='P1',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='P2',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='P3',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='P4',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='P5',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='P6',
            field=models.TextField(max_length=400),
        ),
    ]
