# Generated by Django 2.2.5 on 2019-09-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20190927_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg',
            new_name='Comentario',
        ),
    ]
